export const consultorios = [
  {
    id: 1,
    name: "Consultorio 1",
    description:
      "Espacio optimizado y funcional, ideal para atención individual.",
    features: [
      "Espacio optimizado y funcional",
      "Dos cómodos sillones individuales",
      "Mesa auxiliar para apoyo",
      "Mantiene la calidez de Pisama",
    ],
    price: 250,
    images: [
      "/images/consultorio1-1.jpg",
      "/images/consultorio1-2.jpg",
      "/images/consultorio1-3.jpg",
    ],
    video: "/images/consultorio1.mp4",
  },
  {
    id: 2,
    name: "Consultorio 2",
    description: "Ambiente cálido y moderno para psicoterapia y coaching.",
    features: [
      "Decoración acogedora",
      "Sillón + escritorio",
      "Ventana con luz natural",
      "Perfecto para consultas online",
    ],
    price: 250,
    images: [
      "/images/consultorio2-1.jpg",
      "/images/consultorio2-2.jpg",
      "/images/consultorio2-3.jpg",
    ],
    video: "/images/consultorio2.mp4",
  },
  {
    id: 3,
    name: "Consultorio 3",
    description: "Ambiente cálido y moderno para psicoterapia y coaching.",
    features: [
      "Decoración acogedora",
      "Sillón + escritorio",
      "Ventana con luz natural",
      "Perfecto para consultas online",
    ],
    price: 250,
    images: [
      "/images/consultorio3-1.jpg",
      "/images/consultorio3-2.jpg",
      "/images/consultorio3-3.jpg",
    ],
    video: "/images/consultorio3.mp4",
  },
  {
    id: 4,
    name: "Consultorio 4",
    description: "Ambiente cálido y moderno para psicoterapia y coaching.",
    features: [
      "Decoración acogedora",
      "Sillón + escritorio",
      "Ventana con luz natural",
      "Perfecto para consultas online",
    ],
    price: 250,
    images: [
      "/images/consultorio4-1.jpg",
      "/images/consultorio4-2.jpg",
      "/images/consultorio4-3.jpg",
    ],
    video: "/images/consultorio4.mp4",
  },
  {
    id: 5,
    name: "Consultorio 5",
    description: "Ambiente cálido y moderno para psicoterapia y coaching.",
    features: [
      "Decoración acogedora",
      "Sillón + escritorio",
      "Ventana con luz natural",
      "Perfecto para consultas online",
    ],
    price: 200,
    images: [
      "/images/consultorio5-1.jpg",
      "/images/consultorio5-2.jpg",
      "/images/consultorio5-3.jpg",
    ],
    video: "/images/consultorio5.mp4",
  },
  {
    id: 6,
    name: "Consultorio 6",
    description: "Ambiente cálido y moderno para psicoterapia y coaching.",
    features: [
      "Decoración acogedora",
      "Sillón + escritorio",
      "Ventana con luz natural",
      "Perfecto para consultas online",
    ],
    price: 250,
    images: [
      "/images/consultorio6-1.jpg",
      "/images/consultorio6-2.jpg",
      "/images/consultorio6-3.jpg",
    ],
    video: "/images/consultorio6.mp4",
  },
];

export const otrasAreas = [
  {
    id: "espera",
    name: "Sala de espera",
    description: "Un espacio cómodo para recibir a tus pacientes.",
    features: ["Asientos amplios", "Ambiente climatizado", "Música ambiental"],
    images: [
      "/images/espera1.jpg",
      "/images/espera2.jpg",
      "/images/espera3.jpg",
    ],
    video: "/images/espera.mp4",
  },
  {
    id: "baños",
    name: "Baños",
    description: "Modernos, higiénicos y accesibles para todos.",
    features: ["Accesibilidad total", "Limpieza garantizada"],
    images: ["/images/banio1.jpg", "/images/banio2.jpg", "/images/banio3.jpg"],
    video: "/images/banio.mp4",
  },
  {
    id: "descanso",
    name: "Sala de descanso",
    description: "Un lugar privado para profesionales.",
    features: ["Cafetera", "Microondas", "Sofás confortables"],
    images: [
      "/images/descanso1.jpg",
      "/images/descanso2.jpg",
      "/images/descanso3.jpg",
    ],
    video: "/images/descanso.mp4",
  },
  {
    id: "fachada",
    name: "Fachada",
    description: "Ubicación visible y de fácil acceso en Montevideo.",
    features: ["Acceso principal", "Estacionamiento cercano"],
    images: [
      "/images/fachada1.jpg",
      "/images/fachada2.jpg",
      "/images/fachada3.jpg",
    ],
    video: "/images/fachada.mp4",
  },
  {
    id: "acceso",
    name: "Acceso con código",
    description: "Ingreso seguro con sistema de códigos personalizado.",
    features: ["Control de acceso", "Mayor seguridad"],
    images: [
      "/images/acceso1.jpg",
      "/images/acceso2.jpg",
      "/images/acceso3.jpg",
    ],
    video: "/images/acceso.mp4",
  },
];
